FROM openjdk:21-jdk-slim
MAINTAINER Phi
ENV SPRING_PROFILES_ACTIVE=prod
ENV EMAIL_DAILY_UPDATE=${EMAIL_DAILY_UPDATE}
ENV EMAIL_SWIMMING_UPDATE=${EMAIL_SWIMMING_UPDATE}
ENV DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
EXPOSE 8082
COPY target/weather.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
