FROM openjdk:21-jdk-slim
LABEL maintainer = "Phi"

ARG EMAIL_DAILY_UPDATE
ARG EMAIL_SWIMMING_UPDATE
ARG DISCORD_WEBHOOK_URL
ARG MAIL_USERNAME
ARG MAIL_PASSWORD

ENV EMAIL_DAILY_UPDATE=$EMAIL_DAILY_UPDATE
ENV EMAIL_SWIMMING_UPDATE=$EMAIL_SWIMMING_UPDATE
ENV DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD

EXPOSE 8082
COPY target/weather.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
